defaults: &defaults
  working_directory: ~/analytics-clj
  docker:
    - image: clojure:lein

version: 2

jobs:
  clj-kondo:
    docker:
      - image: cljkondo/clj-kondo:2026.01.12
    steps:
      - checkout
      - run: clj-kondo --lint .

  docs:
    <<: *defaults
    steps:
      - checkout
      - run: lein deps
      - run: lein codox

  test:
    <<: *defaults
    steps:
      - checkout
      - run: lein deps
      - run: lein check
      - run: lein test

  publish:
    <<: *defaults
    steps:
      - checkout
      - run: |
          # Grab the numerical version of the tag
          tag_version=${CIRCLE_TAG#v}

          # Extract the version from the project.clj
          project_version=$(awk 'NR==1 {print $3}' project.clj | sed -e 's/"//g')

          # Fail if the tags do not match
          test ${tag_version} = ${project_version} || exit 1

          # Fail if the tag version is not in CHANGELOG
          grep "^Version" CHANGELOG.md | grep "${tag_version}" || exit 1

      - run: lein deps
      - run: lein deploy

workflows:
  version: 2
  test_and_publish:
    jobs:
      - clj-kondo:
          filters:
            tags:
              only: /.*/
      - docs:
          filters:
            tags:
              only: /.*/
      - test:
          filters:
            tags:
              only: /.*/
      - publish:
          context: clojars-publish
          requires:
            - clj-kondo
            - docs
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
